# Generated by Django 3.2 on 2021-08-17 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, choices=[('Décolleté', 'Décolleté'), ("D'Orsay", "D'Orsay"), ('V-neck', 'V-neck'), ('Mules', 'Mules'), ('Sabot', 'Sabot'), ('Clogs', 'Clogs'), ('Mocassins', 'Mocassins'), ('Brogues', 'Brogues'), ('Sandals', 'Sandals'), ('Lace-up', 'Lace-up'), ('Gladiators', 'Gladiators'), ('Boots', 'Boots'), ('Boots Texan', 'Boots Texan'), ('Ankle Boots', 'Ankle Boots'), ('Sock Boots', 'Sock Boots'), ('Cuissardes', 'Cuissardes'), ('Sneakers', 'Sneakers'), ('Pumps', 'Pumps'), ('T-Strap', 'T-Strap'), ('Cross-Strap', 'Cross-Strap'), ('Diagonal-Strap', 'Diagonal-Strap'), ('Ankle-Strap', 'Ankle-Strap'), ('Beatles', 'Beatles'), ('Bikers', 'Bikers'), ('Mary Jane', 'Mary Jane'), ('Ballet Flats', 'Ballets Flats'), ('Ballroom Dance Shoes', 'Ballroom Dance Shoes'), ('Espadrille', 'Espadrille'), ('Fantasy', 'Fantasy'), ('Corset', 'Corset'), ('Cut Out', 'Cut Out'), ('Flip-flops', 'Flip-flops')], max_length=200, null=True)),
                ('platform', models.BooleanField(default=False)),
                ('slingback', models.BooleanField(default=False)),
                ('toe', models.CharField(blank=True, choices=[('Peep', 'Peep'), ('Open', 'Open'), ('Rounded', 'Rounded'), ('Pointed', 'Pointed'), ('Square', 'Square'), ('Almond', 'Almond')], max_length=20, null=True)),
                ('style', models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Sport', 'Sport'), ('Tennis', 'Tennis'), ('Elegant', 'Elegant'), ('Cerimony', 'Cerimony'), ('Wedding', 'Wedding'), ('Office', 'Office'), ('Evening', 'Evening'), ('Sea', 'Sea'), ('Home', 'Home')], max_length=200, null=True)),
                ('SKU', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, choices=[('30', '30'), ('30.5', '30.5'), ('31', '31'), ('31.5', '31.5'), ('32', '32'), ('32.5', '32.5'), ('33', '33'), ('33.5', '33.5'), ('34', '34'), ('34.5', '34.5'), ('35', '35'), ('35.5', '35.5'), ('36', '36'), ('36.5', '36.5'), ('37', '37'), ('37.5', '37.5'), ('38', '38'), ('38.5', '38.5'), ('39', '39'), ('39.5', '39.5'), ('40', '40'), ('40.5', '40.5'), ('41', '41'), ('41.5', '41.5'), ('42', '42'), ('42.5', '42.5'), ('43', '43'), ('43.5', '43.5'), ('44', '44'), ('44.5', '44.5'), ('45', '45')], max_length=5, null=True)),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Nude', 'Nude'), ('Gray', 'Gray'), ('White', 'White'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Red', 'Red'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Green', 'Green'), ('Orange', 'Orange'), ('Fuchsia', 'Fuchsia'), ('Blue', 'Blue'), ('Azure', 'Azure'), ('Silver', 'Silver'), ('Purple', 'Purple'), ('Wheat', 'Wheat'), ('Glitter', 'Glitter')], max_length=200, null=True)),
                ('sole_color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Nude', 'Nude'), ('Gray', 'Gray'), ('White', 'White'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Red', 'Red'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Green', 'Green'), ('Orange', 'Orange'), ('Fuchsia', 'Fuchsia'), ('Blue', 'Blue'), ('Azure', 'Azure'), ('Silver', 'Silver'), ('Purple', 'Purple'), ('Wheat', 'Wheat'), ('Glitter', 'Glitter')], max_length=200, null=True)),
                ('heel_height', models.IntegerField(blank=True, default=0, null=True)),
                ('heel_kind', models.CharField(blank=True, choices=[('Large', 'Large'), ('Wedge', 'Wedge'), ('Stiletto', 'Stiletto'), ('Cone', 'Cone'), ('Blade', 'Blade'), ('Kitten', 'Kitten'), ('Spool', 'Spool')], max_length=20, null=True)),
                ('plateau_height', models.IntegerField(blank=True, default=0, null=True)),
                ('sole_material', models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Suede leather', 'Suede leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Synthetics', 'Synthetics'), ('Microfiber', 'Microfiber'), ('Plastic', 'Plastic'), ('Vinyl', 'Vinyl'), ('Polyethylene', 'Polyethylene'), ('Other', 'Other')], max_length=30, null=True)),
                ('lining_material', models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Suede leather', 'Suede leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Synthetics', 'Synthetics'), ('Microfiber', 'Microfiber'), ('Plastic', 'Plastic'), ('Vinyl', 'Vinyl'), ('Polyethylene', 'Polyethylene'), ('Other', 'Other')], max_length=30, null=True)),
                ('upper_material', models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Suede leather', 'Suede leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Synthetics', 'Synthetics'), ('Microfiber', 'Microfiber'), ('Plastic', 'Plastic'), ('Vinyl', 'Vinyl'), ('Polyethylene', 'Polyethylene'), ('Other', 'Other')], max_length=30, null=True)),
                ('season', models.CharField(blank=True, choices=[('Autumn', 'Autumn'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20, null=True)),
                ('year', models.IntegerField(default=0)),
                ('comfort', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('plant_fit', models.CharField(blank=True, choices=[('Narrow', 'Narrow'), ('Normal', 'Normal'), ('Wide', 'Wide')], max_length=30, null=True)),
                ('state', models.CharField(blank=True, choices=[('New', 'New'), ('Good conditions', 'Good conditions'), ('To be cleaned', 'To be cleaned'), ('Need service', 'Need service')], max_length=30, null=True)),
                ('available', models.BooleanField(default=True)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('favourite', models.BooleanField(default=False)),
                ('cart', models.BooleanField(default=False)),
                ('ordered', models.IntegerField(blank=True, default=0, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('delivered_date', models.CharField(blank=True, max_length=200, null=True)),
                ('returned_date', models.CharField(blank=True, max_length=200, null=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('paginate', models.IntegerField(blank=True, choices=[('8', '8'), ('32', '32'), ('128', '128'), ('0', '0')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe')),
            ],
        ),
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.shoebrand'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='cart_user',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoe',
            name='delivered_user',
            field=models.ManyToManyField(blank=True, related_name='delivered_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoe',
            name='favourite_user',
            field=models.ManyToManyField(blank=True, related_name='favourite_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoe',
            name='ordered_user',
            field=models.ManyToManyField(blank=True, related_name='ordered_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoe',
            name='terminated_user',
            field=models.ManyToManyField(blank=True, related_name='terminated_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoe',
            name='urgent_user',
            field=models.ManyToManyField(blank=True, related_name='urgent_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoe',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
