# Generated by Django 3.2 on 2021-05-26 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='favourite_user',
            field=models.ManyToManyField(blank=True, related_name='favourite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
