# Generated by Django 3.2 on 2021-04-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='model_name',
            new_name='style',
        ),
        migrations.AddField(
            model_name='shoe',
            name='comfortable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoe',
            name='heel_kind',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='plateau_heitht',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoe',
            name='season',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='year',
            field=models.FloatField(default=0),
        ),
    ]
