# Generated by Django 3.2 on 2021-05-26 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0002_shoe_favourite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='urgent_user',
            field=models.ManyToManyField(blank=True, related_name='urgent_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
