# Generated by Django 3.2 on 2021-06-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_auto_20210605_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='ordered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
