# Generated by Django 3.2 on 2021-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_auto_20210421_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='plateau_heitht',
            new_name='plateau_height',
        ),
        migrations.AddField(
            model_name='shoe',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
