# Generated by Django 3.2 on 2021-05-29 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0003_shoe_urgent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='user',
        ),
        migrations.AddField(
            model_name='shoe',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
