# Generated by Django 3.2 on 2021-06-28 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0003_alter_shoe_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='terminated_user',
            field=models.ManyToManyField(blank=True, related_name='terminated_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
