# Generated by Django 3.2 on 2021-05-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoe_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
