# Generated by Django 3.2 on 2021-08-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_accountconfig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfig',
            name='paginate',
            field=models.IntegerField(choices=[(8, '8'), (32, '32'), (128, '128'), (0, '0')]),
        ),
    ]
