# Generated by Django 3.2 on 2021-04-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_auto_20210421_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='comfortable',
            new_name='comfort',
        ),
    ]
