# Generated by Django 3.2 on 2021-05-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_shoe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='ordered',
            new_name='cart',
        ),
    ]
