# Generated by Django 3.2 on 2021-05-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_rename_ordered_shoe_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='delivered_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoe',
            name='returned_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
