# Generated by Django 3.2 on 2021-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_rename_comfortable_shoe_comfort'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
