# Generated by Django 3.2 on 2021-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_shoe_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
