# Generated by Django 3.2 on 2021-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_shoe_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='order_by',
            field=models.CharField(default='pk', editable=False, max_length=200),
        ),
    ]
