# Generated by Django 3.2 on 2021-08-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_alter_accountconfig_paginate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfig',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
