# Generated by Django 3.2 on 2021-04-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_alter_shoe_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='state',
            field=models.CharField(blank=True, default='New', max_length=200, null=True),
        ),
    ]
