# Generated by Django 3.2 on 2021-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_shoe_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='order_by',
            field=models.CharField(default='heel_height', editable=False, max_length=200),
        ),
    ]
