# Generated by Django 3.2 on 2021-05-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_alter_shoe_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, choices=[('Décolleté', 'Décolleté'), ("D'Orsay", "D'Orsay"), ('V-neck', 'V-neck'), ('Mules', 'Mules'), ('Sabot', 'Sabot'), ('Clogs', 'Clogs'), ('Mocassins', 'Mocassins'), ('Brogues', 'Brogues'), ('Sandals', 'Sandals'), ('Lace-up', 'Lace-up'), ('Gladiators', 'Gladiators'), ('Boots', 'Boots'), ('Ankle Boots', 'Ankle Boots'), ('Sock Boots', 'Sock Boots'), ('Cuissardes', 'Cuissardes'), ('Sneakers', 'Sneakers'), ('Pumps', 'Pumps'), ('T-Strap', 'T-Strap'), ('Cross-Strap', 'Cross-Strap'), ('Diagonal-Strap', 'Diagonal-Strap'), ('Ankle-Strap', 'Ankle-Strap'), ('Texas', 'Texas'), ('Beatles', 'Beatles'), ('Bikers', 'Bikers'), ('Mary Jane', 'Mary Jane'), ('Ballet Flats', 'Ballets Flats'), ('Ballroom Dance Shoes', 'Ballroom Dance Shoes'), ('Espadrille', 'Espadrille'), ('Fantasy', 'Fantasy'), ('Corset', 'Corset'), ('Cut Out', 'Cut Out'), ('Flip-flops', 'Flip-flops')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='season',
            field=models.CharField(blank=True, choices=[('Autumn', 'Autumn'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20, null=True),
        ),
    ]
