# Generated by Django 3.2 on 2021-05-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_auto_20210519_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='plant_fit',
            field=models.CharField(blank=True, choices=[('Narrow', 'Narrow'), ('Normal', 'Normal'), ('Wide', 'Wide')], max_length=30, null=True),
        ),
    ]
