# Generated by Django 3.2 on 2021-04-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_auto_20210421_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
