# Generated by Django 3.2 on 2021-05-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_alter_shoe_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='order_by',
        ),
    ]
