# Generated by Django 3.2 on 2021-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0010_shoe_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
