# Generated by Django 3.2 on 2021-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_shoe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
