# Generated by Django 3.2 on 2021-05-21 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0012_alter_shoe_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='carts_users',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
