# Generated by Django 3.2 on 2021-05-21 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0013_shoe_carts_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='carts_users',
        ),
        migrations.AddField(
            model_name='shoe',
            name='cart_old',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='cart',
        ),
        migrations.AddField(
            model_name='shoe',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
