# Generated by Django 3.2 on 2021-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_alter_shoe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='heel_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='plateau_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
