# Generated by Django 3.2 on 2021-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0014_auto_20210421_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='season',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('DEC', 'December')], default='AW', max_length=10),
        ),
    ]
