# Generated by Django 3.2 on 2021-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0015_alter_shoe_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, choices=[('AW', 'AW'), ('SS', 'SS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='season',
            field=models.CharField(blank=True, choices=[('AW', 'AW'), ('SS', 'SS')], max_length=10, null=True),
        ),
    ]
