# Generated by Django 3.2 on 2021-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0016_auto_20210421_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, choices=[('Décolleté', 'Décolleté'), ('Décolleté Slingback', 'Décolleté Slingback'), ('Mules', 'Mules'), ('Sabot', 'Sabot'), ('Sandals', 'Sandals'), ('Wedges', 'Wedges'), ('Boots', 'Boots'), ('Sneakers', 'Sneakers'), ('Pumps', 'Pumps')], max_length=200, null=True),
        ),
    ]
