# Generated by Django 3.2 on 2021-04-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0023_auto_20210422_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='heel_kind',
            field=models.CharField(blank=True, choices=[('Large', 'Large'), ('Wedge', 'Wedge'), ('Stiletto', 'Stiletto'), ('Brown', 'Bwoen')], max_length=20, null=True),
        ),
    ]
