# Generated by Django 3.2 on 2021-04-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0024_alter_shoe_heel_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='SKU',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='peep_toe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, choices=[('Décolleté', 'Décolleté'), ('Décolleté Slingback', 'Décolleté Slingback'), ('Mules', 'Mules'), ('Sabot', 'Sabot'), ('Open Toe', 'Open Toe'), ('Sandals', 'Sandals'), ('Wedges', 'Wedges'), ('Platform', 'Platform'), ('Ankle Boots', 'Ankle Boots'), ('Boots', 'Boots'), ('Sneakers', 'Sneakers'), ('Pumps', 'Pumps'), ('T-Strap', 'T-Strap'), ('Ankle-Stra', 'Ankle-Strap'), ('Texas', 'Texas')], max_length=200, null=True),
        ),
    ]
