# Generated by Django 3.2 on 2021-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0027_auto_20210422_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='style',
            field=models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Sport', 'Sport'), ('Tennis', 'Tennis'), ('Elegant', 'Elegant'), ('Cerimony', 'Cerimony'), ('Wedding', 'Wedding'), ('Sea', 'Sea')], max_length=200, null=True),
        ),
    ]
