# Generated by Django 3.2 on 2021-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0028_alter_shoe_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='season',
            field=models.CharField(blank=True, choices=[('AW', 'Autumn Winter'), ('SS', 'Spring Summer')], max_length=10, null=True),
        ),
    ]
