# Generated by Django 3.2 on 2021-04-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0031_auto_20210423_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Grey', 'Grey'), ('White', 'White'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Red', 'Red'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Green', 'Green'), ('Orange', 'Orange'), ('Fuxia', 'Fuxia'), ('Blue', 'Blue')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='heel_kind',
            field=models.CharField(blank=True, choices=[('Large', 'Large'), ('Wedge', 'Wedge'), ('Stiletto', 'Stiletto')], max_length=20, null=True),
        ),
    ]
