# Generated by Django 3.2 on 2021-04-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0032_auto_20210423_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='heel_kind',
            field=models.CharField(blank=True, choices=[('Large', 'Large'), ('Wedge', 'Wedge'), ('Stiletto', 'Stiletto'), ('Cone', 'Cone')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='style',
            field=models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Sport', 'Sport'), ('Tennis', 'Tennis'), ('Elegant', 'Elegant'), ('Cerimony', 'Cerimony'), ('Wedding', 'Wedding'), ('Office', 'Office'), ('Evening', 'Evening'), ('Sea', 'Sea')], max_length=200, null=True),
        ),
    ]
