# Generated by Django 3.2 on 2021-04-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0033_auto_20210423_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='state',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Good conditions', 'Good conditions'), ('To be cleaned', 'To be cleaned'), ('Need service', 'Need service')], max_length=30, null=True),
        ),
    ]
