# Generated by Django 3.2 on 2021-04-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0034_alter_shoe_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='heel_kind',
            field=models.CharField(blank=True, choices=[('Large', 'Large'), ('Wedge', 'Wedge'), ('Stiletto', 'Stiletto'), ('Cone', 'Cone'), ('Blade', 'Blade')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='material',
            field=models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
