# Generated by Django 3.2 on 2021-04-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0036_alter_shoe_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='material',
            field=models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Microfibra', 'Microfibra'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
