# Generated by Django 3.2 on 2021-04-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0038_auto_20210423_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='season',
            field=models.CharField(blank=True, choices=[('Autumn Winter', 'Autumn Winter'), ('Spring Summer', 'Spring Summer')], max_length=20, null=True),
        ),
    ]
