# Generated by Django 3.2 on 2021-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0040_alter_shoe_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='pointed_toe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='lining_material',
            field=models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Microfibra', 'Microfibra'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='sole_material',
            field=models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Microfibra', 'Microfibra'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='upper_material',
            field=models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Microfibra', 'Microfibra'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
