# Generated by Django 3.2 on 2021-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0041_auto_20210425_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='peep_toe',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='pointed_toe',
        ),
        migrations.AddField(
            model_name='shoe',
            name='toe',
            field=models.CharField(blank=True, choices=[('Peep', 'Peep'), ('Rounded', 'Rounded'), ('Pointed', 'Pointed')], max_length=20, null=True),
        ),
    ]
