# Generated by Django 3.2 on 2021-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0042_auto_20210425_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, choices=[('Décolleté', 'Décolleté'), ('Mules', 'Mules'), ('Sabot', 'Sabot'), ('Clogs', 'Clogs'), ('Mocassins', 'Mocassins'), ('Brogues', 'Brogues'), ('Open Toe', 'Open Toe'), ('Sandals', 'Sandals'), ('Wedges', 'Wedges'), ('Ankle Boots', 'Ankle Boots'), ('Lace-up', 'Lace-up'), ('Gladiators', 'Gladiators'), ('Boots', 'Boots'), ('Sneakers', 'Sneakers'), ('Pumps', 'Pumps'), ('T-Strap', 'T-Strap'), ('Ankle-Strap', 'Ankle-Strap'), ('Texas', 'Texas')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='toe',
            field=models.CharField(blank=True, choices=[('Peep', 'Peep'), ('Rounded', 'Rounded'), ('Pointed', 'Pointed'), ('Square', 'Square'), ('Almond', 'Almond')], max_length=20, null=True),
        ),
    ]
