# Generated by Django 3.2 on 2021-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0044_auto_20210426_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='heel_kind',
            field=models.CharField(blank=True, choices=[('Large', 'Large'), ('Wedge', 'Wedge'), ('Stiletto', 'Stiletto'), ('Cone', 'Cone'), ('Blade', 'Blade'), ('Kitten', 'Kitten'), ('Spool', 'Spool')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, choices=[('Décolleté', 'Décolleté'), ("D'Orsay", "D'Orsay"), ('V-neck', 'V-neck'), ('Mules', 'Mules'), ('Sabot', 'Sabot'), ('Clogs', 'Clogs'), ('Mocassins', 'Mocassins'), ('Brogues', 'Brogues'), ('Sandals', 'Sandals'), ('Ankle Boots', 'Ankle Boots'), ('Lace-up', 'Lace-up'), ('Gladiators', 'Gladiators'), ('Boots', 'Boots'), ('Ankle Boots', 'Ankle Boots'), ('Sock Boots', 'Sock Boots'), ('Cuissardes', 'Cuissardes'), ('Sneakers', 'Sneakers'), ('Pumps', 'Pumps'), ('T-Strap', 'T-Strap'), ('Cross-Strap', 'Cross-Strap'), ('Diagonal-Strap', 'Diagonal-Strap'), ('Ankle-Strap', 'Ankle-Strap'), ('Texas', 'Texas'), ('Beatles', 'Beatles'), ('Bikers', 'Bikers'), ('Mary Jane', 'Mary Jane'), ('Ballet Flats', 'Ballets Flats'), ('Ballroom Dance Shoes', 'Ballroom Dance Shoes'), ('Espadrille', 'Espadrille'), ('Fantasy', 'Fantasy'), ('Corset', 'Corset'), ('Cut Out', 'Cut Out')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='toe',
            field=models.CharField(blank=True, choices=[('Peep', 'Peep'), ('Open', 'Open'), ('Rounded', 'Rounded'), ('Pointed', 'Pointed'), ('Square', 'Square'), ('Almond', 'Almond')], max_length=20, null=True),
        ),
    ]
