# Generated by Django 3.2 on 2021-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0046_auto_20210426_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='style',
            field=models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Sport', 'Sport'), ('Tennis', 'Tennis'), ('Elegant', 'Elegant'), ('Cerimony', 'Cerimony'), ('Wedding', 'Wedding'), ('Office', 'Office'), ('Evening', 'Evening'), ('Sea', 'Sea'), ('Home', 'Home')], max_length=200, null=True),
        ),
    ]
