# Generated by Django 3.2 on 2021-04-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0048_auto_20210426_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoe',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
