# Generated by Django 3.2 on 2021-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0050_alter_shoe_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('White', 'White'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Red', 'Red'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Green', 'Green'), ('Orange', 'Orange'), ('Fuchsia', 'Fuchsia'), ('Blue', 'Blue'), ('Azure', 'Azure'), ('Silver', 'Silver'), ('Purple', 'Purple'), ('Wheat', 'Wheat'), ('Glitter', 'Glitter')], max_length=200, null=True),
        ),
    ]
