# Generated by Django 3.2 on 2021-04-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0052_auto_20210428_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe_second_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoe_second_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe_second_image'),
            preserve_default=False,
        ),
    ]
