# Generated by Django 3.2 on 2021-04-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0053_auto_20210428_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_second_image',
        ),
        migrations.AddField(
            model_name='shoe_second_image',
            name='shoe_second_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe'),
        ),
    ]
