# Generated by Django 3.2 on 2021-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0053_shoe_second_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='lining_material',
            field=models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Suede leather', 'Suede leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Synthetics', 'Synthetics'), ('Microfiber', 'Microfiber'), ('Plastic', 'Plastic'), ('Vinyl', 'Vinyl'), ('Polyethylene', 'Polyethylene'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='sole_material',
            field=models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Suede leather', 'Suede leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Synthetics', 'Synthetics'), ('Microfiber', 'Microfiber'), ('Plastic', 'Plastic'), ('Vinyl', 'Vinyl'), ('Polyethylene', 'Polyethylene'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='upper_material',
            field=models.CharField(blank=True, choices=[('Leather', 'Leather'), ('Patent leather', 'Patent leather'), ('Suede leather', 'Suede leather'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric'), ('Wood', 'Wood'), ('Cork', 'Cork'), ('Synthetics', 'Synthetics'), ('Microfiber', 'Microfiber'), ('Plastic', 'Plastic'), ('Vinyl', 'Vinyl'), ('Polyethylene', 'Polyethylene'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
