# Generated by Django 3.2 on 2021-05-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0055_auto_20210503_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe_second_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoeImages',
        ),
        migrations.AddField(
            model_name='shoe_second_image',
            name='shoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe'),
        ),
    ]
