# Generated by Django 3.2 on 2021-05-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0056_auto_20210503_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image',
        ),
    ]
