# Generated by Django 3.2 on 2021-05-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0057_remove_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
