# Generated by Django 3.2 on 2021-05-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0058_shoe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image',
        ),
    ]
