# Generated by Django 3.2 on 2021-05-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0059_remove_shoe_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoe_second_image',
            new_name='ShoeImage',
        ),
    ]
