# Generated by Django 3.2 on 2021-05-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0061_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='shoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.brand'),
        ),
    ]
