# Generated by Django 3.2 on 2021-05-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0062_brand_shoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='shoe',
            new_name='shoeBrand',
        ),
    ]
